"""Archive -> demo roster.

The archive's value is diversity, and diversity that is only claimed is worth nothing. So
selection deliberately spreads across the **measured speed** axis rather than taking the
top-N by fitness: a lane represented by three near-identical elites is a lane whose
archive column may as well have been one cell.

Concretely, per lane: the best elite overall, plus the best from the fastest-occupied and
slowest-occupied speed bins. A judge watching the demo should be able to see one scout
outrun another and be told, truthfully, that nobody designed either of them.

Output is `assets/scenarios/demo_roster.yaml`, in the same `RobotSpec` shape
`sim/robot.py` already builds by hand, so nothing downstream changes when it appears.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
from pathlib import Path

import numpy as np
import yaml

from ...sim.robot import CHASSIS, LANES
from .genome import decode_spec, lane_of

ROSTER_PATH = Path(__file__).resolve().parents[3] / "assets" / "scenarios" / (
    "demo_roster.yaml")

#: How many distinct elites to take per lane. Three is enough to show a spread without
#: making the roster unreadable on the dashboard.
PER_LANE = 3


def load(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    d = np.load(Path(path) / "archive.npz")
    return d["solution"], d["objective"], d["measures"]


def pick(solutions: np.ndarray, objective: np.ndarray, measures: np.ndarray,
         per_lane: int = PER_LANE) -> dict[str, list[int]]:
    """Per lane: the best elite, then the extremes of the occupied speed range.

    Ties and ordering break on index so the roster is reproducible -- selecting a
    different demo swarm on each run would make rehearsed timings meaningless.
    """
    out: dict[str, list[int]] = {}
    lanes = measures[:, 0].astype(int)
    speeds = measures[:, 1]
    for li, lane in enumerate(LANES):
        idx = np.nonzero(lanes == li)[0]
        if len(idx) == 0:
            out[lane] = []
            continue
        chosen: list[int] = []
        # 1. the best in the lane
        chosen.append(int(idx[np.lexsort((idx, -objective[idx]))[0]]))
        # 2. and 3. the extremes of measured speed, best-in-bin
        for reverse in (True, False):
            order = np.lexsort((idx, -speeds[idx] if reverse else speeds[idx]))
            for j in order:
                cand = int(idx[j])
                if cand not in chosen:
                    chosen.append(cand)
                    break
            if len(chosen) >= per_lane:
                break
        out[lane] = chosen[:per_lane]
    return out


def build_roster(solutions: np.ndarray, picked: dict[str, list[int]],
                 per_lane_count: int) -> list[dict]:
    """Expand the picked elites into `per_lane_count` robots per lane.

    Chassis is round-robined across every elite, not tied to it: locomotion is what makes
    the terrain meaningful, and a roster where every carrier is legged has quietly
    deleted the river.
    """
    specs: list[dict] = []
    n = 0
    for lane in LANES:
        elites = picked.get(lane) or []
        if not elites:
            continue
        for k in range(per_lane_count):
            genome = solutions[elites[k % len(elites)]]
            # The archive's lane measure is derived from the genome's own actuator gene,
            # so these agree by construction. Checking anyway: if they ever diverge the
            # roster would file a carrier as a scout and the failure would show up as
            # "the demo swarm is bad at rescuing" three days before the demo.
            if lane_of(genome) != lane:
                raise ValueError(
                    f"elite filed under {lane!r} decodes to {lane_of(genome)!r}; "
                    "the archive and the genome disagree about the lane"
                )
            chassis = CHASSIS[k % len(CHASSIS)]
            spec = decode_spec(genome, f"r{n:03d}", chassis)
            d = asdict(spec)
            d["elite"] = k % len(elites)
            specs.append(d)
            n += 1
    return specs


def write(specs: list[dict], path: Path, meta: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# GENERATED by training/mapelites/select.py -- do not edit by hand.\n"
        "# Every body here was discovered by MAP-Elites, not designed. Regenerate with\n"
        "#   uv run python -m swarmmind.training.mapelites.select\n"
        f"# {meta}\n\n" + yaml.safe_dump({"robots": specs}, sort_keys=False),
        # Explicit, to match the reader in sim/robot.py. This artefact is the one
        # training output that crosses machines as a file rather than as numbers, so
        # it must not be written in whatever encoding the training box's locale had.
        encoding="utf-8",
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="archive -> demo_roster.yaml")
    ap.add_argument("--archive", type=Path, default=Path("runs/mapelites"))
    ap.add_argument("--per-lane", type=int, default=PER_LANE)
    ap.add_argument("--count", type=int, default=8, help="robots per lane in the roster")
    ap.add_argument("--out", type=Path, default=ROSTER_PATH)
    args = ap.parse_args(argv)

    sol, obj, meas = load(args.archive)
    if len(sol) == 0:
        print("  archive is empty; nothing to select")
        return 1
    picked = pick(sol, obj, meas, args.per_lane)
    for lane in LANES:
        got = picked.get(lane) or []
        speeds = [f"{meas[i, 1]:.2f}" for i in got]
        fits = [f"{obj[i]:.2f}" for i in got]
        print(f"  {lane:<8} {len(got)} elites   speeds {speeds}   fitness {fits}")
    empty = [ln for ln in LANES if not picked.get(ln)]
    if empty:
        print(f"  WARNING: no elite for {empty} -- those lanes fall back to the "
              f"hand-set archetypes")

    specs = build_roster(sol, picked, args.count)
    write(specs, args.out, {"elites": len(sol), "per_lane": args.per_lane,
                            "robots": len(specs)})
    print(f"  {len(specs)} robots -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
