"""Copy only robot observations into the team's private input.

No simulator reference crosses this boundary. Counts refer to reports/work, not to
the number of people hidden in the scenario. Radio-disconnected units are excluded.
"""

from collections import Counter

import numpy as np

from ...contracts import topics
from ...perception.tracker import CONFIRMED, RESOLVED
from ...sim import grid
from ...sim.robot import LANES


def capture(world, executor, tracker, bus, snapshot_id: str) -> dict:
    connected = world.in_comms & (world.status == 0)
    ix, iy = grid.world_to_cell(world.pos[:, 0], world.pos[:, 1], world.cell, world.shape)
    sectors_at = world.sector_of_cell[iy, ix]
    counts = np.bincount(sectors_at[connected], minlength=len(world.sector_ids))
    contacts = Counter()
    resolved = Counter()
    for r in sorted(tracker.reports, key=lambda r: r.id):
        if r.state in (CONFIRMED, RESOLVED):
            sid = world._sector_at(tuple(r.pos))
            (contacts if r.state == CONFIRMED else resolved)[sid] += 1
    # Announced tasks are knowledge generated by Tier 2 from its own belief store.
    backlog = {sid: Counter() for sid in world.sector_ids}
    for task in bus.latest(topics.TASKS_AVAILABLE) or []:
        backlog[world._sector_at(task.target)][task.kind] += 1
    zones = {world._sector_at(z) for z in [world.scn.base, *world.scn.extraction_zones]}
    sectors = [{
        "id": sid, "explored": round(float(world.sector_explored_pct[k]), 3),
        "hazard": round(float(world.sector_hazard_known[k]), 3),
        "connected": int(counts[k]), "contacts": contacts[sid],
        "resolved_reports": resolved[sid], "backlog": dict(sorted(backlog[sid].items())),
        "collection": sid in zones, "priority": int(world.sector_priority[k]),
        "abandoned": bool(world.sector_abandoned[k]),
    } for k, sid in enumerate(world.sector_ids)]
    lanes = {}
    for k, lane in enumerate(LANES):
        mask = connected & (world.actuator == k)
        lanes[lane] = {"connected": int(mask.sum()),
                       "battery": round(float(world.battery[mask].mean()), 3)
                       if mask.any() else None}
    return {"id": snapshot_id, "sim_time": round(world.t, 3),
            "duration": world.scn.mission_duration_s, "sectors": sectors, "lanes": lanes}


def observe_event(event: dict) -> dict | None:
    """An allowlist: never forward raw simulator text/positions to the agents."""
    if event.get("kind") not in {
        "task_awarded", "task_orphaned", "victim_found", "victim_cleared",
        "victim_rescued", "report_dismissed", "robot_reconnected",
    }:
        return None
    return {k: event[k] for k in ("t", "kind", "task", "robot") if k in event}
